### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by mclau152** [AdamKyle/flare#105]
how to run?

**Comment by AdamKyle** [comment]
@mclau152  more context is needed for your question

**Comment by mclau152** [comment]
how do you run this github project?

**Comment by AdamKyle** [comment]
I havent done the docs on how to set up on a server, but you can get it started through the [development docs](https://github.com/AdamKyle/flare/wiki/Planes-of-Tlessa-Development-Documentation)

Closing because this isn't a bug.
