### ISSUE TITLE
[BUG] Doesn't redirect to login if session is expired

### ISSUE THREAD

**Issue by sumsar10171** [AdamKyle/flare#16]
If your session is expired and you try to open the kingdom modal, it doesn't redirect to the login page.
It will instead stall as soon on the picture.

![image](https://user-images.githubusercontent.com/5278216/121804060-c7fcad80-cc44-11eb-9c64-19ea1fe06a8d.png)

**Comment by AdamKyle** [comment]
Thank you, I will fix this asap.

**Comment by AdamKyle** [comment]
Closing - Fixed in 1.0.3
