### ISSUE TITLE
[BUG] Cant train Skills

### ISSUE THREAD

**Issue by p48sk** [AdamKyle/flare#18]
**Describe the bug**
I cant train skill. The screen turns grey and i have to reload the page again.

**To Reproduce**
1. Go to Character Sheet
2. Click train on Accuracy
3. Screen turns grey, nothing is clickable you have to reload the page.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/86559585/124444258-b3609080-dd7e-11eb-8bd4-b5f3b1bdbc20.png)
![image](https://user-images.githubusercontent.com/86559585/124444289-ba879e80-dd7e-11eb-8bdc-28debaf48c49.png)
![image](https://user-images.githubusercontent.com/86559585/124444217-a93e9200-dd7e-11eb-9f8b-2119e3a0b260.png)

**Browser and Version**
-  Chrome Version 91.0.4472.124 64 bit

**Smartphone (please complete the following information):**
 - Device: Personal Computer
 - Windows 10
 - Chrome Version 91.0.4472.124 64 bit

Please note: I can only support listed devices in chrome dev tools (IE Chrome Console) I have hade sure that the game does work at the appropriate breakpoints.

**Comment by AdamKyle** [comment]
@p48sk  Thank you. This will be fixed.

**Comment by AdamKyle** [comment]
Closing as we solved it and I cannot replicate in either firefox or chrome
