### ISSUE TITLE
[BUG] Items in Inventory cant be destroyed

### ISSUE THREAD

**Issue by p48sk** [AdamKyle/flare#19]
**Describe the bug**
Items in Inventory cant be destroyed

**To Reproduce**
1. Go to Character Sheet
2. Click on the blue Actions Button on any item
3. Click on destroy  -> The screen turns now grey. You have to reload the page to do something again.

**Screenshots**
![image](https://user-images.githubusercontent.com/86559585/124444826-48638980-dd7f-11eb-8898-f5af03d236f7.png)
![image](https://user-images.githubusercontent.com/86559585/124444933-616c3a80-dd7f-11eb-92a1-1997a140fffa.png)

**Comment by AdamKyle** [comment]
@p48sk  Thank you this will be fixed

**Comment by AdamKyle** [comment]
Closing as we solved it and I cannot replicate via chrome or firefox.
