### ISSUE TITLE
"npm run dev" not working - external issue

### ISSUE THREAD

**Issue by michelangelo404** [AdamKyle/flare#25]
Hi,
when I try to run "npm run dev" this message appears:

_$ TAILWIND_MODE = build mix
"TAILWIND_MODE" is not recognized as an internal or external command,
  an executable program or batch file._

I don't know why this happens, anyway, another issue is that I can't install some laravel horizon dependencies like **pcntl** due to my OS (Windows 10), is there any way to run this game in windows 10?

Thank you.

**Comment by AdamKyle** [comment]
I am unsure for your npm issues as I just run yarn run watch for development.

As for the second issue: No, this was built on a mac. So linux or mac would be needed, or you could dockerize the application and then you can use docker on windows to run it, but that means setting up things for redis and so on.

**Comment by michelangelo404** [comment]
> I am unsure for your npm issues as I just run yarn run watch for development.
> 
> As for the second issue: No, this was built on a mac. So linux or mac would be needed, or you could dockerize the application and then you can use docker on windows to run it, but that means setting up things for redis and so on.

For the first issue, it seems like when I enter "npm run dev" the command start to execute a list of commands inside the file "package.json" under "scripts".

**Comment by AdamKyle** [comment]
I am not sure if this would help, But I do not use npm, I use yarn. (should be no difference, but OS might be the cause?)

- yarn install
- yarn dev/watch/prod

I have never tried to get Tlessa going on windows, so I'm sorry I could not be of much help.

**Comment by michelangelo404** [comment]
I tried to run the following commands:
- yarn install works;
- yarn dev not working;
- yarn watch not working, freeze at _"Child mini-css-extract-plugin D:\Downloads\flare-master\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[6].use[1]!D:\Downloads\flare-master\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[6].use[2]!D:\Downloads\flare-master\resources\css\tailwind.css compiled successfully (85c698193f4d91f7)                                                   webpack 5.70.0 compiled successfully in 34604 ms (15fbdb63766175c6)"_
- yarn prod working.
I will look for alternatives and close this issue.
