### ISSUE TITLE
[BUG]  how to run the game on php 7.4

### ISSUE THREAD

**Issue by fisher762** [AdamKyle/flare#28]
hello
after i install the script and all it requirements i got this error when try to create new account  :
syntax error, unexpected '|', expecting ';' or '{'

[](phpstorm://open?file=D%3A%5Cxampp%5Chtdocs%5Cflare%5Capp%5CFlare%5CBuilders%5CCharacter%5CAttackDetails%5CCharacterAttackBuilder.php&line=281)D:\xampp\htdocs\flare\app\Flare\Builders\Character\AttackDetails\CharacterAttackBuilder.php:281

i think because i have php version 7.4
is there any way to run it on php 7? i dont want to update my php version

**Comment by AdamKyle** [comment]
You do not, the game only runs on php 8.0 with no plans for backward compatability with other php versions.

**Comment by fisher762** [comment]
ok .. thank  you very much
