### ISSUE TITLE
[Feature Request] Fixing typos/spellchecking/improving game text

### ISSUE THREAD

**Issue by bloodyshade** [AdamKyle/flare#30]
> ## ATTN
>
> If you are planning to implement this feature, all tests must pass. Failure to do so will have the feature rejected until they do.
>
> No feature is allowed to "require" payment of any kind for the player to be able to access. They can how ever be restricted by level, skill, plane, gold or any other existing "gate" in game.
>
> If this feature implements or makes use of timers, you must make sure the player can log out, in, navigate to any page and come back and see the timer still running.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Spend time as possible improving the text in the game, including fixing typos.

**Describe alternatives you've considered**
The only alternative in this case would be to leave things as is, and while that is fine for the most part, I would like to contribute as I can to the game's overall improvement.

**Additional context**

**How would you as the player benefit from this additional feature?**
Improving the readability of the game as a whole would benefit every player. (Personally, perfectionism is a curse.)

**How would the community benefit from this feature?**
Improving the readability of the game as a whole would benefit every player.

**Does this feature already exists and if so are you expanding upon it?**
Yes, mostly just fixing typos and improving text where possible.

**Are you planning to implement this or are you expecting me to?**
I'm planning on working on this myself as time allows.

**Does this feature break any existing feature?**
It should not.

**Does this feature fix and existing bug?**
Only to the extent that I might find things wrongly named in the code (for example invalid variable names) in which case those are changed to the supposedly correct ones. At which point we can further deliberate/discuss before PRs are accepted.

**Comment by AdamKyle** [comment]
Merged and accepted.
