### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Mistik** [AdamKyle/flare#48]
is there a demo up and running of this game?

**Comment by AdamKyle** [comment]
The server had to be shut down, because I could not afford the costs. The game will be back when I have a new job, see this [Reddit Post](https://www.reddit.com/r/PBBG/comments/11xmixs/planes_of_tlessa_announcement/)

**Comment by d47081** [comment]
What about hardware requirements?

btw, few screenshots could be useful on readme page.
