### ISSUE TITLE
[BUG] Dev guide wiki page 'import data' command needs to be updated

### ISSUE THREAD

**Issue by bradcis** [AdamKyle/flare#54]
On https://github.com/AdamKyle/flare/wiki/Planes-of-Tlessa-Development-Documentation#commands-to-run, it says to run the following command to load in maps, game races, etc.:
`php artisan import:data`
This should be updated to:
`php artisan import:game-data`

Thanks!

**Comment by bradcis** [comment]
It doesn't look like I can do a pull request on wiki pages or I'd submit that way.

**Comment by AdamKyle** [comment]
Thank you, this has been fixed.
