### ISSUE TITLE
[BUG] - When login or Registe just redirect

### ISSUE THREAD

**Issue by marlon33** [AdamKyle/flare#87]
**Describe the bug**
login and registes doesn't work in my server, i test in xampp and docker, both doesn't work, just redirect

**Browser and Version**
-  Chrome Versão 124.0.6367.63 (Versão oficial) 64 bits

**NodeJs and Version**
v22.0.0

**Yarn and Version**
1.22.22

**Version**
- PHP 8.2
- MySql 8
- REDIS LATEST

**Additional context**
I just clone and configurate all the system, but when i try to registe or login, just redirect

**Comment by AdamKyle** [comment]
I cannot replicate this. Appoligies
