### ISSUE TITLE
[BUG]PHP Deprecated:  parse_url()

### ISSUE THREAD

**Issue by oppiet30** [AdamKyle/flare#97]
**Describe the bug**
PHP Deprecated:  parse_url(): Passing null to parameter #1 ($url) of type string is deprecated in /home/oppie/flare-1/flare-1.5.11/server.php on line 9 - This is with php-8.3.13. I am not filling out the rest.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser and Version**
- e.g. Edge 15, Chrome 45, Safari 74
  - Please note we do not support, nor will we ever support Internet explorer of any version.

**Smartphone (please complete the following information):**

Please note: I can only support listed devices in chrome dev tools (IE Chrome Console) I have hade sure that the game does work at the appropriate breakpoints.

- For those of you on ipad Pro, please play in portrait mode. For some reason landscape mode makes the map all squished and broken.

**Additional context**

**Comment by AdamKyle** [comment]
This has been fixed in this [commit for the upcoming 1.5.12](https://github.com/AdamKyle/flare/commit/492ebb585fa0db8c7cd12f32e246b0ab95d62b7c) Thank you for reporting.
